In [3]:
import pandas as pd

df = pd.read_csv("../cleaned_data/cleaned_vancouver.csv",encoding = "ISO-8859-1")
df.head(3)

,address,price,bedrooms,bath,lot_size,property_age,gross_tax_for_2020,area,Sub-Area/Community,Property_Type,title,style,heating_type,Depth,frontage
0,2070 W 14th Avenue,378800,8.0,4.0,6250,98,10423,Vancouver West,Kitsilano,House,Freehold NonStrata,Reverse 2 Storey w/Bsmt,125,50.00 feet,R2493457
1,2917 W 20th Avenue,428800,5.0,5.0,5129,7,12652,Vancouver West,Arbutus,House,Freehold NonStrata,2 Storey w/Bsmt.,Heat Recovery Ventilator,122.12,42.00 feet
2,2688 W 19th Avenue,380000,6.0,6.0,6240,33,11176,Vancouver West,Arbutus,House,Freehold NonStrata,2 Storey,120,52.00 feet,R2520899

In [4]:
# dummies variable 
dummies = pd.get_dummies(df['Sub-Area/Community'])
dummies.head(3)

,Arbutus,Cambie,Collingwood,Dunbar,Fairview,Fraser East,Fraserview East,Grandview East,Hastings,Hastings Sunrise,...,Point Grey,Quilchena,Renfrew,Renfrew Heights,Shaughnessy,South Cambie,South Vancouver,Southlands,Southwest Marine,Victoria East
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
merged = pd.concat([df, dummies], axis='columns')
merged.head(3)

,address,price,bedrooms,bath,lot_size,property_age,gross_tax_for_2020,area,Sub-Area/Community,Property_Type,...,Point Grey,Quilchena,Renfrew,Renfrew Heights,Shaughnessy,South Cambie,South Vancouver,Southlands,Southwest Marine,Victoria East
0,2070 W 14th Avenue,378800,8.0,4.0,6250,98,10423,Vancouver West,Kitsilano,House,...,0,0,0,0,0,0,0,0,0,0
1,2917 W 20th Avenue,428800,5.0,5.0,5129,7,12652,Vancouver West,Arbutus,House,...,0,0,0,0,0,0,0,0,0,0
2,2688 W 19th Avenue,380000,6.0,6.0,6240,33,11176,Vancouver West,Arbutus,House,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# drop a column from the dummy variables to avoid the dummy variable trap
final = merged.drop(['Sub-Area/Community','Southlands'],axis='columns')
final.head(3)

,address,price,bedrooms,bath,lot_size,property_age,gross_tax_for_2020,area,Property_Type,title,...,Oakridge,Point Grey,Quilchena,Renfrew,Renfrew Heights,Shaughnessy,South Cambie,South Vancouver,Southwest Marine,Victoria East
0,2070 W 14th Avenue,378800,8.0,4.0,6250,98,10423,Vancouver West,House,Freehold NonStrata,...,0,0,0,0,0,0,0,0,0,0
1,2917 W 20th Avenue,428800,5.0,5.0,5129,7,12652,Vancouver West,House,Freehold NonStrata,...,0,0,0,0,0,0,0,0,0,0
2,2688 W 19th Avenue,380000,6.0,6.0,6240,33,11176,Vancouver West,House,Freehold NonStrata,...,0,0,0,0,0,0,0,0,0,0

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [8]:
# drop unecessary columns
final = final.drop(['address','area','Property_Type', 'title', 'style','heating_type', 'Depth', 'frontage'],axis='columns')

In [9]:
X = final.drop('price', axis='columns')
X.head(3)

,bedrooms,bath,lot_size,property_age,gross_tax_for_2020,Arbutus,Cambie,Collingwood,Dunbar,Fairview,...,Oakridge,Point Grey,Quilchena,Renfrew,Renfrew Heights,Shaughnessy,South Cambie,South Vancouver,Southwest Marine,Victoria East
0,8.0,4.0,6250,98,10423,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5.0,5.0,5129,7,12652,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6.0,6.0,6240,33,11176,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
y = final.price
y.head(3)

0    378800
1    428800
2    380000
Name: price, dtype: int64

In [11]:
# create a model
model.fit(X,y)

LinearRegression()

In [12]:
model.score(X,y)

0.7676618139714617